// Generated by gencpp from file dynamixel_hr_ros/ChainState.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_HR_ROS_MESSAGE_CHAINSTATE_H
#define DYNAMIXEL_HR_ROS_MESSAGE_CHAINSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_hr_ros
{
template <class ContainerAllocator>
struct ChainState_
{
  typedef ChainState_<ContainerAllocator> Type;

  ChainState_()
    : id()
    , angle()  {
    }
  ChainState_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> const> ConstPtr;

}; // struct ChainState_

typedef ::dynamixel_hr_ros::ChainState_<std::allocator<void> > ChainState;

typedef boost::shared_ptr< ::dynamixel_hr_ros::ChainState > ChainStatePtr;
typedef boost::shared_ptr< ::dynamixel_hr_ros::ChainState const> ChainStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_hr_ros::ChainState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_hr_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dynamixel_hr_ros': ['/home/woutkanters/Fontys_SCARA_Arm/src/dynamixel_hr_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7771c1e7a4b4d36d3cc6bf12733a6fa0";
  }

  static const char* value(const ::dynamixel_hr_ros::ChainState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7771c1e7a4b4d36dULL;
  static const uint64_t static_value2 = 0x3cc6bf12733a6fa0ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_hr_ros/ChainState";
  }

  static const char* value(const ::dynamixel_hr_ros::ChainState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] id\n\
float32[] angle\n\
#float32[] speed\n\
#bool[] moving\n\
";
  }

  static const char* value(const ::dynamixel_hr_ros::ChainState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChainState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_hr_ros::ChainState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_hr_ros::ChainState_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_HR_ROS_MESSAGE_CHAINSTATE_H
