set(_CATKIN_CURRENT_PACKAGE "pcl_extraction")
set(pcl_extraction_VERSION "0.0.0")
set(pcl_extraction_MAINTAINER "ruud <ruud@todo.todo>")
set(pcl_extraction_PACKAGE_FORMAT "1")
set(pcl_extraction_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all-dev")
set(pcl_extraction_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(pcl_extraction_BUILDTOOL_DEPENDS "catkin")
set(pcl_extraction_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_extraction_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(pcl_extraction_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(pcl_extraction_TEST_DEPENDS )
set(pcl_extraction_DOC_DEPENDS )
set(pcl_extraction_DEPRECATED "")