set(_CATKIN_CURRENT_PACKAGE "scara_setup_description")
set(scara_setup_description_VERSION "0.0.0")
set(scara_setup_description_MAINTAINER "jeroen <jeroen@todo.todo>")
set(scara_setup_description_PACKAGE_FORMAT "1")
set(scara_setup_description_BUILD_DEPENDS )
set(scara_setup_description_BUILD_EXPORT_DEPENDS )
set(scara_setup_description_BUILDTOOL_DEPENDS "catkin")
set(scara_setup_description_BUILDTOOL_EXPORT_DEPENDS )
set(scara_setup_description_EXEC_DEPENDS )
set(scara_setup_description_RUN_DEPENDS )
set(scara_setup_description_TEST_DEPENDS )
set(scara_setup_description_DOC_DEPENDS )
set(scara_setup_description_DEPRECATED "")