set(_CATKIN_CURRENT_PACKAGE "scara_setup_dynamixel")
set(scara_setup_dynamixel_VERSION "0.0.0")
set(scara_setup_dynamixel_MAINTAINER "jeroen <jeroen@todo.todo>")
set(scara_setup_dynamixel_PACKAGE_FORMAT "1")
set(scara_setup_dynamixel_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(scara_setup_dynamixel_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(scara_setup_dynamixel_BUILDTOOL_DEPENDS "catkin")
set(scara_setup_dynamixel_BUILDTOOL_EXPORT_DEPENDS )
set(scara_setup_dynamixel_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(scara_setup_dynamixel_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(scara_setup_dynamixel_TEST_DEPENDS )
set(scara_setup_dynamixel_DOC_DEPENDS )
set(scara_setup_dynamixel_DEPRECATED "")