set(_CATKIN_CURRENT_PACKAGE "scara_setup_moveit")
set(scara_setup_moveit_VERSION "0.2.0")
set(scara_setup_moveit_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(scara_setup_moveit_PACKAGE_FORMAT "1")
set(scara_setup_moveit_BUILD_DEPENDS "scara_setup_description")
set(scara_setup_moveit_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "scara_setup_description" "moveit_simple_controller_manager" "moveit_ros_control_interface" "ros_controllers")
set(scara_setup_moveit_BUILDTOOL_DEPENDS "catkin")
set(scara_setup_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(scara_setup_moveit_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "scara_setup_description" "moveit_simple_controller_manager" "moveit_ros_control_interface" "ros_controllers")
set(scara_setup_moveit_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "scara_setup_description" "moveit_simple_controller_manager" "moveit_ros_control_interface" "ros_controllers")
set(scara_setup_moveit_TEST_DEPENDS )
set(scara_setup_moveit_DOC_DEPENDS )
set(scara_setup_moveit_DEPRECATED "")