// Generated by gencpp from file pcl_capturing/position_request.msg
// DO NOT EDIT!


#ifndef PCL_CAPTURING_MESSAGE_POSITION_REQUEST_H
#define PCL_CAPTURING_MESSAGE_POSITION_REQUEST_H

#include <ros/service_traits.h>


#include <pcl_capturing/position_requestRequest.h>
#include <pcl_capturing/position_requestResponse.h>


namespace pcl_capturing
{

struct position_request
{

typedef position_requestRequest Request;
typedef position_requestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct position_request
} // namespace pcl_capturing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_capturing::position_request > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::pcl_capturing::position_request&) { return value(); }
};

template<>
struct DataType< ::pcl_capturing::position_request > {
  static const char* value()
  {
    return "pcl_capturing/position_request";
  }

  static const char* value(const ::pcl_capturing::position_request&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_capturing::position_requestRequest> should match 
// service_traits::MD5Sum< ::pcl_capturing::position_request > 
template<>
struct MD5Sum< ::pcl_capturing::position_requestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_capturing::position_request >::value();
  }
  static const char* value(const ::pcl_capturing::position_requestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_capturing::position_requestRequest> should match 
// service_traits::DataType< ::pcl_capturing::position_request > 
template<>
struct DataType< ::pcl_capturing::position_requestRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_capturing::position_request >::value();
  }
  static const char* value(const ::pcl_capturing::position_requestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_capturing::position_requestResponse> should match 
// service_traits::MD5Sum< ::pcl_capturing::position_request > 
template<>
struct MD5Sum< ::pcl_capturing::position_requestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_capturing::position_request >::value();
  }
  static const char* value(const ::pcl_capturing::position_requestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_capturing::position_requestResponse> should match 
// service_traits::DataType< ::pcl_capturing::position_request > 
template<>
struct DataType< ::pcl_capturing::position_requestResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_capturing::position_request >::value();
  }
  static const char* value(const ::pcl_capturing::position_requestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_CAPTURING_MESSAGE_POSITION_REQUEST_H
