set(_CATKIN_CURRENT_PACKAGE "pcl_capturing")
set(pcl_capturing_VERSION "0.0.0")
set(pcl_capturing_MAINTAINER "ruud <ruud@todo.todo>")
set(pcl_capturing_PACKAGE_FORMAT "1")
set(pcl_capturing_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all-dev")
set(pcl_capturing_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "libpcl-all")
set(pcl_capturing_BUILDTOOL_DEPENDS "catkin")
set(pcl_capturing_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_capturing_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "libpcl-all")
set(pcl_capturing_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "libpcl-all")
set(pcl_capturing_TEST_DEPENDS )
set(pcl_capturing_DOC_DEPENDS )
set(pcl_capturing_DEPRECATED "")