set(_CATKIN_CURRENT_PACKAGE "scara_setup_bringup")
set(scara_setup_bringup_VERSION "0.0.0")
set(scara_setup_bringup_MAINTAINER "jeroen <jeroen@todo.todo>")
set(scara_setup_bringup_PACKAGE_FORMAT "1")
set(scara_setup_bringup_BUILD_DEPENDS "gazebo_ros" "scara_setup_description" "scara_setup_control")
set(scara_setup_bringup_BUILD_EXPORT_DEPENDS "gazebo_ros" "scara_setup_description" "scara_setup_control" "rosserial_python" "gazebo_ros_control")
set(scara_setup_bringup_BUILDTOOL_DEPENDS "catkin")
set(scara_setup_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(scara_setup_bringup_EXEC_DEPENDS "gazebo_ros" "scara_setup_description" "scara_setup_control" "rosserial_python" "gazebo_ros_control")
set(scara_setup_bringup_RUN_DEPENDS "gazebo_ros" "scara_setup_description" "scara_setup_control" "rosserial_python" "gazebo_ros_control")
set(scara_setup_bringup_TEST_DEPENDS )
set(scara_setup_bringup_DOC_DEPENDS )
set(scara_setup_bringup_DEPRECATED "")