set(_CATKIN_CURRENT_PACKAGE "scara_setup_control")
set(scara_setup_control_VERSION "0.0.0")
set(scara_setup_control_MAINTAINER "jeroen <jeroen@todo.todo>")
set(scara_setup_control_PACKAGE_FORMAT "1")
set(scara_setup_control_BUILD_DEPENDS "controller_manager" "robot_state_publisher" "dynamixel_controllers" "dynamixel_msgs")
set(scara_setup_control_BUILD_EXPORT_DEPENDS "controller_manager" "robot_state_publisher" "dynamixel_controllers" "dynamixel_msgs" "controller_interface" "ros_controllers")
set(scara_setup_control_BUILDTOOL_DEPENDS "catkin")
set(scara_setup_control_BUILDTOOL_EXPORT_DEPENDS )
set(scara_setup_control_EXEC_DEPENDS "controller_manager" "robot_state_publisher" "dynamixel_controllers" "dynamixel_msgs" "controller_interface" "ros_controllers")
set(scara_setup_control_RUN_DEPENDS "controller_manager" "robot_state_publisher" "dynamixel_controllers" "dynamixel_msgs" "controller_interface" "ros_controllers")
set(scara_setup_control_TEST_DEPENDS )
set(scara_setup_control_DOC_DEPENDS )
set(scara_setup_control_DEPRECATED "")