// Generated by gencpp from file pclcaptureing_positioning/position_request.msg
// DO NOT EDIT!


#ifndef PCLCAPTUREING_POSITIONING_MESSAGE_POSITION_REQUEST_H
#define PCLCAPTUREING_POSITIONING_MESSAGE_POSITION_REQUEST_H

#include <ros/service_traits.h>


#include <pclcaptureing_positioning/position_requestRequest.h>
#include <pclcaptureing_positioning/position_requestResponse.h>


namespace pclcaptureing_positioning
{

struct position_request
{

typedef position_requestRequest Request;
typedef position_requestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct position_request
} // namespace pclcaptureing_positioning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pclcaptureing_positioning::position_request > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::pclcaptureing_positioning::position_request&) { return value(); }
};

template<>
struct DataType< ::pclcaptureing_positioning::position_request > {
  static const char* value()
  {
    return "pclcaptureing_positioning/position_request";
  }

  static const char* value(const ::pclcaptureing_positioning::position_request&) { return value(); }
};


// service_traits::MD5Sum< ::pclcaptureing_positioning::position_requestRequest> should match 
// service_traits::MD5Sum< ::pclcaptureing_positioning::position_request > 
template<>
struct MD5Sum< ::pclcaptureing_positioning::position_requestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pclcaptureing_positioning::position_request >::value();
  }
  static const char* value(const ::pclcaptureing_positioning::position_requestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pclcaptureing_positioning::position_requestRequest> should match 
// service_traits::DataType< ::pclcaptureing_positioning::position_request > 
template<>
struct DataType< ::pclcaptureing_positioning::position_requestRequest>
{
  static const char* value()
  {
    return DataType< ::pclcaptureing_positioning::position_request >::value();
  }
  static const char* value(const ::pclcaptureing_positioning::position_requestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pclcaptureing_positioning::position_requestResponse> should match 
// service_traits::MD5Sum< ::pclcaptureing_positioning::position_request > 
template<>
struct MD5Sum< ::pclcaptureing_positioning::position_requestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pclcaptureing_positioning::position_request >::value();
  }
  static const char* value(const ::pclcaptureing_positioning::position_requestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pclcaptureing_positioning::position_requestResponse> should match 
// service_traits::DataType< ::pclcaptureing_positioning::position_request > 
template<>
struct DataType< ::pclcaptureing_positioning::position_requestResponse>
{
  static const char* value()
  {
    return DataType< ::pclcaptureing_positioning::position_request >::value();
  }
  static const char* value(const ::pclcaptureing_positioning::position_requestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCLCAPTUREING_POSITIONING_MESSAGE_POSITION_REQUEST_H
